name: AIUB Notice Checker

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-notices:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - 
        name: Run script
        env:
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
      - 
        name: Commit and push changes
        if: success()
        run: |
          git add aiub_notices.db
          git commit -m "Update aiub_notices.db"
          git push
