name: AIUB Notice Checker

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-notices:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - 
        name: Run script
        env:
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
        
      - 
        name: Check for changes
        if: success()
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes found. Proceeding with commit..."
          else
            echo "No changes found. Skipping commit..."
          fi
      - 
        name: Configure Git
        if: steps.check-for-changes.output == 'Changes found. Proceeding with commit...'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://${{ secrets.GIT_AUTH }}@github.com/origamiofficial/aiub-notice-checker.git
      - 
        name: Commit changes
        if: steps.check-for-changes.output == 'Changes found. Proceeding with commit...'
        run: |
          git add aiub_notices.db
          git commit -m "Update aiub_notices.db"
          git push